### ISSUE TITLE
Overlapping instances error

### ISSUE THREAD

**Issue by jonathanlking** [dorchard/sessions-in-haskell#1]
When compiling/running with GHC 8.0.2 I get overlapping instance errors for `Show (Var ...)` in `Data/Type/Set.hs`.

These can be ignored (I think) by adding the `{-# OVERLAPPING #-}` pragma for the 'x','y','z' instances of show, or by enabling the `OverlappingInstances` extension (`ghci examples.lhs -XOverlappingInstances` and setting `extensions: OverlappingInstances` in the cabal file).

(I think this work is really cool!)

**Comment by dorchard** [comment]
Thank you very much for pointing this out! It has now been fixed. Best, Dominic
